spring:
  application:
    name: auth-project
  # MySQL datasource configurations
  # If your spring application is using some kind of database-related library
  # (like Spring Data JPA, Hibernate, Flyway), you need to provide these
  # configurations. Otherwise, your application will throw an error.
  datasource:
    url: jdbc:mysql://localhost:3306/database
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
